### ISSUE TITLE
Makefile (or Ninja/CMake)?

### ISSUE THREAD

**Issue by SchrodingerZhu** [ICEYSELF/cclib#2]
We still need a makefile/ninja/cmake I guess.
It will be more helpful if we add tests later.
We can set USE_STD flag.

For `nostd` version, the following flags can be considered:
- `nostartfiles`
- `ffreestanding`
- `nostdlib`

**Comment by ICEYSELF** [comment]
A hand written Makefile has been added.

**Comment by SchrodingerZhu** [comment]
fixed.
